# Generated by Django 3.2.9 on 2021-11-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke_time', models.DateTimeField(auto_now_add=True, verbose_name='연기 발생 시간')),
            ],
            options={
                'ordering': ('-smoke_time',),
            },
        ),
    ]
