# Generated by Django 2.2.5 on 2021-11-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke_time', models.DateTimeField(auto_now_add=True, verbose_name='연기 발생 시간')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naga.Shop')),
            ],
            options={
                'ordering': ('-smoke_time',),
            },
        ),
    ]
